# Generated by Django 3.1.7 on 2021-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
